language: python
python: 
  - "2.7"
install: 
  - "pip install tox-travis"
script: 
  - tox
after_success:
  - coveralls
after_failure:
  - more .tox/log/* | cat
  - more .tox/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: always
