language: python
python: "3.6"
env:
  matrix:
    - TOXENV=check
    - TOXENV=py27
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=pypy
install: "pip install tox-travis"
script: tox
after_failure:
  - more .tox/log/* | cat
  - more .tox/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_failure: always
